'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WSProfesores
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSProfesores.WebServiceProfesorSoap")>  _
    Public Interface WebServiceProfesorSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarFaculdates", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarFaculdates() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarFaculdates", ReplyAction:="*")>  _
        Function ListarFaculdatesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCategoria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarCategoria() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarCategoria", ReplyAction:="*")>  _
        Function ListarCategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarProfesores", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListarProfesores() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListarProfesores", ReplyAction:="*")>  _
        Function ListarProfesoresAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarProfesors", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function BuscarProfesors(ByVal codigo As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarProfesors", ReplyAction:="*")>  _
        Function BuscarProfesorsAsync(ByVal codigo As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CrearProfesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CrearProfesor(ByVal profesor As WSProfesores.ModeloProfesor) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CrearProfesor", ReplyAction:="*")>  _
        Function CrearProfesorAsync(ByVal profesor As WSProfesores.ModeloProfesor) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActuaizarProfesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActuaizarProfesor(ByVal profesor As WSProfesores.ModeloProfesor) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActuaizarProfesor", ReplyAction:="*")>  _
        Function ActuaizarProfesorAsync(ByVal profesor As WSProfesores.ModeloProfesor) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarProfesor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EliminarProfesor(ByVal profesor As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EliminarProfesor", ReplyAction:="*")>  _
        Function EliminarProfesorAsync(ByVal profesor As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ModeloProfesor
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cedulaField As String
        
        Private codigoField As String
        
        Private nombreField As String
        
        Private apellidoField As String
        
        Private direccionField As String
        
        Private celularField As String
        
        Private correoField As String
        
        Private cod_facultadField As String
        
        Private cod_categoriaField As String
        
        Private salarioField As String
        
        Private estatusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Cedula() As String
            Get
                Return Me.cedulaField
            End Get
            Set
                Me.cedulaField = value
                Me.RaisePropertyChanged("Cedula")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
                Me.RaisePropertyChanged("Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
                Me.RaisePropertyChanged("Apellido")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
                Me.RaisePropertyChanged("Direccion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property celular() As String
            Get
                Return Me.celularField
            End Get
            Set
                Me.celularField = value
                Me.RaisePropertyChanged("celular")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
                Me.RaisePropertyChanged("correo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property cod_facultad() As String
            Get
                Return Me.cod_facultadField
            End Get
            Set
                Me.cod_facultadField = value
                Me.RaisePropertyChanged("cod_facultad")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property cod_categoria() As String
            Get
                Return Me.cod_categoriaField
            End Get
            Set
                Me.cod_categoriaField = value
                Me.RaisePropertyChanged("cod_categoria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property salario() As String
            Get
                Return Me.salarioField
            End Get
            Set
                Me.salarioField = value
                Me.RaisePropertyChanged("salario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property estatus() As String
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
                Me.RaisePropertyChanged("estatus")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebServiceProfesorSoapChannel
        Inherits WSProfesores.WebServiceProfesorSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceProfesorSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSProfesores.WebServiceProfesorSoap)
        Implements WSProfesores.WebServiceProfesorSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements WSProfesores.WebServiceProfesorSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements WSProfesores.WebServiceProfesorSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Function ListarFaculdates() As System.Data.DataTable Implements WSProfesores.WebServiceProfesorSoap.ListarFaculdates
            Return MyBase.Channel.ListarFaculdates
        End Function
        
        Public Function ListarFaculdatesAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements WSProfesores.WebServiceProfesorSoap.ListarFaculdatesAsync
            Return MyBase.Channel.ListarFaculdatesAsync
        End Function
        
        Public Function ListarCategoria() As System.Data.DataTable Implements WSProfesores.WebServiceProfesorSoap.ListarCategoria
            Return MyBase.Channel.ListarCategoria
        End Function
        
        Public Function ListarCategoriaAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements WSProfesores.WebServiceProfesorSoap.ListarCategoriaAsync
            Return MyBase.Channel.ListarCategoriaAsync
        End Function
        
        Public Function ListarProfesores() As System.Data.DataSet Implements WSProfesores.WebServiceProfesorSoap.ListarProfesores
            Return MyBase.Channel.ListarProfesores
        End Function
        
        Public Function ListarProfesoresAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WSProfesores.WebServiceProfesorSoap.ListarProfesoresAsync
            Return MyBase.Channel.ListarProfesoresAsync
        End Function
        
        Public Function BuscarProfesors(ByVal codigo As String) As System.Data.DataSet Implements WSProfesores.WebServiceProfesorSoap.BuscarProfesors
            Return MyBase.Channel.BuscarProfesors(codigo)
        End Function
        
        Public Function BuscarProfesorsAsync(ByVal codigo As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WSProfesores.WebServiceProfesorSoap.BuscarProfesorsAsync
            Return MyBase.Channel.BuscarProfesorsAsync(codigo)
        End Function
        
        Public Function CrearProfesor(ByVal profesor As WSProfesores.ModeloProfesor) As Boolean Implements WSProfesores.WebServiceProfesorSoap.CrearProfesor
            Return MyBase.Channel.CrearProfesor(profesor)
        End Function
        
        Public Function CrearProfesorAsync(ByVal profesor As WSProfesores.ModeloProfesor) As System.Threading.Tasks.Task(Of Boolean) Implements WSProfesores.WebServiceProfesorSoap.CrearProfesorAsync
            Return MyBase.Channel.CrearProfesorAsync(profesor)
        End Function
        
        Public Function ActuaizarProfesor(ByVal profesor As WSProfesores.ModeloProfesor) As Boolean Implements WSProfesores.WebServiceProfesorSoap.ActuaizarProfesor
            Return MyBase.Channel.ActuaizarProfesor(profesor)
        End Function
        
        Public Function ActuaizarProfesorAsync(ByVal profesor As WSProfesores.ModeloProfesor) As System.Threading.Tasks.Task(Of Boolean) Implements WSProfesores.WebServiceProfesorSoap.ActuaizarProfesorAsync
            Return MyBase.Channel.ActuaizarProfesorAsync(profesor)
        End Function
        
        Public Function EliminarProfesor(ByVal profesor As String) As Boolean Implements WSProfesores.WebServiceProfesorSoap.EliminarProfesor
            Return MyBase.Channel.EliminarProfesor(profesor)
        End Function
        
        Public Function EliminarProfesorAsync(ByVal profesor As String) As System.Threading.Tasks.Task(Of Boolean) Implements WSProfesores.WebServiceProfesorSoap.EliminarProfesorAsync
            Return MyBase.Channel.EliminarProfesorAsync(profesor)
        End Function
    End Class
End Namespace
